### ISSUE TITLE
\STDOUT not writeable - why?

### ISSUE THREAD

**Issue by prolic** [amphp/log#1]
To reproduce:

`composer require prooph/event-store-client dev-master`

Then execute this script:

```
<?php
declare(strict_types=1);
namespace Prooph\EventStoreClient;
use Amp\Loop;

require __DIR__ . '/../vendor/autoload.php';

Loop::run(function () {
    $settings = ConnectionSettings::create()
        ->useConsoleLogger()
        ->enableVerboseLogging()
        ->build();

    $connection = EventStoreAsyncConnectionFactory::createFromEndPoint(
        new EndPoint('eventstore', 1113),
        $settings
    );

});
```

Outputs:
```
Fatal error: Uncaught Amp\ByteStream\ClosedException: The stream is not writable in /home/sasa/code/event-store-client/vendor/amphp/byte-stream/lib/ResourceOutputStream.php:165
Stack trace:
#0 /home/sasa/code/event-store-client/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(144): Amp\ByteStream\ResourceOutputStream->send('[2018-11-17 16:...', false)
#1 /home/sasa/code/event-store-client/vendor/amphp/log/src/StreamHandler.php(56): Amp\ByteStream\ResourceOutputStream->write('[2018-11-17 16:...')
#2 /home/sasa/code/event-store-client/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Amp\Log\StreamHandler->write(Array)
#3 /home/sasa/code/event-store-client/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/sasa/code/event-store-client/vendor/monolog/monolog/src/Monolog/Logger.php(532): Monolog\Logger->addRecord(100, 'EventStoreNodeC...', Array)
#5 /home/sasa/code/event-store-client/src/Internal/EventStoreConnectionLogicHandle in /home/sasa/code/event-store-client/vendor/amphp/byte-stream/lib/ResourceOutputStream.php on line 165
```

**Comment by bwoebi** [comment]
First: this stacktrace is within the shutdown sequence, when objects are being destroyed.

It's not writable because the watcher has been closed. Note that early objects are typically destroyed in order of instantiation (the order is actually not well defined at all, but it effectively behaves like that as long as no objects were destroyed yet). So, your ResourceOutputStream is destroyed before the EventStoreAsyncNodeConnection instance ... which calls into the logger, which calls into the resource output stream ;-)

There's one thing we could do: set a $destroyed flag in ResourceOutputStream::__destruct and silently discard writes then without failing. (This at least fixes the issue at hand)
I don't feel sure about that @kelunik @trowski, but this indeed might alllow for clean shutdowns - I've already encountered that myself.

**Comment by kelunik** [comment]
Silently discarding the writes just hides the issue, but doesn't fix it. We should probably do blocking writes in that situation instead?

**Comment by bwoebi** [comment]
Doing a blocking write still hides a problem: the write will be non-blocking if we are not destroyed yet. And may not write everything if the output buffer gets full.
And forcing a blocking write of the remaining buffer is... well... blocking on streams happening to have full buffers.
So that's not a viable option.

I think I however could be fine with "attempt to write as much as possible non-blockingly", which would be consistent with current behavior after loop, before destruction. (So to speak: "undestroy" the object and happily continue if methods are called after__destruct() [this only ever should happen in shutdown, so it's safe].) And I guess that will be enough for most cases outside of an event loop, in shutdown sequence.

**Comment by enumag** [comment]
bump, it would be great to have this fixed... until then the usability of this library is kinda questionable

**Comment by enumag** [comment]
@kelunik @trowski Can you give me some tip how to implement it correctly?

**Comment by kelunik** [comment]
@enumag Do you have a simple reproduction script without external dependencies?

**Comment by kelunik** [comment]
@enumag @prolic Any news here? We've fixed https://github.com/amphp/byte-stream/issues/58 since this issue has been opened, is that related?

**Comment by prolic** [comment]
I'll check it out

**Comment by prolic** [comment]
Sorry it took me so long. I tested this and cannot reproduce the issue anymore. Seems to be fixed. Thank you!
